version: '3'

services:
  portainer_templates:
    image: nginx:alpine
    container_name: "portainer-templates"
    expose:
      - "80"
    volumes:
      - ~/docker-bay/volumes/portainer/templates/templates.json:/usr/share/nginx/html/templates.json
    networks:
      - traefik

  portainer:
    image: portainer/portainer
    container_name: "portainer-application"
    command: --templates http://templates/templates.json --host=unix:///var/run/docker.sock
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/docker-bay/volumes/portainer/data:/data
    labels:
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.local"

  watchtower:
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik:
    external:
      name: traefik_webgateway