version: 3

services:
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    labels:
      - traefik.port=8080    
      - traefik.backend=adminer
      - traefik.frontend.rule=Host:adminer.local
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_webgateway