version: '3'

services:
  dockerbay_adminer:
    image: adminer:latest
    container_name: "dockerbay-adminer"
    restart: always
    networks:
      - traefik
    ports:
       - "8181:8080"
    labels:
      - "traefik.port=8080"    
      - "traefik.backend=dockerbay_adminer"
      - "traefik.frontend.rule=Host:adminer.dockerbay"

networks:
  traefik:
    external:
      name: traefik_webgateway