version: "3"

services:
  dockerbay_ungit:
    container_name: dockerbay_ungit
    build:
      context: ./
      dockerfile: Dockerfile
    image: ungit
    ports:
      - "8448:8448"
    volumes: 
      - ~/docker-bay/workspaces:/repo
    container_name: "dockerbay-ungit"
    working_dir: /repo
    networks:
      - traefik
    # user: "ungit"
    labels:
      - "traefik.port=8448"
      - "traefik.backend=dockerbay_ungit"
      - "traefik.frontend.rule=Host:ungit.dockerbay"
    stdin_open: true
    tty: true

networks:
  traefik:
    external:
      name: traefik_webgateway