version: '3'

services:

  #-TRAEFIK-zero-conf
  traefik:
    container_name: traefik
    restart: always    
    image: traefik:latest
    environment:
      - DOMAIN=${GLOBAL_DOMAIN}
      - TZ="Europe/Paris"
    command: --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    volumes:
      - ${TRAEFIK_DATA_VOLUME}:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.port=8080
      - traefik.backend=proxy
      - traefik.frontend.rule=Host:traefik.${GLOBAL_DOMAIN}
      - traefik.frontend.auth.basic=${GLOBAL_BASIC_AUTH_USER}:${GLOBAL_BASIC_AUTH_PASSWORD}
    ports:
      - 80:80
      - 443:443
    networks:
      - gateway_web

networks:
  gateway_web:
    external:
      name: gateway_web
