version: '3'

services:
   mysql:
     container_name: mysql
     image: mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: example_database
       MYSQL_USER: mysql-user
       MYSQL_PASSWORD: mysql-user
    labels:
      - traefik.port=3306    
      - traefik.backend=mysql
     volumes:
       - ~/docker-bay/volumes/mysql-data:/var/lib/mysql
     networks:
       - traefik

networks:
  traefik:
    external:
      name: traefik_webgateway