version: '3'

services:
  adminmongo:
    container_name: adminmongo
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        GUI_PASSWORD: "${GUI_PASSWORD}"
    restart: always
    labels:
      - traefik.port=1234
      - traefik.backend=adminmongo
      - traefik.frontend.rule=Host:adminmongo.local
    ports:
      - 1234:1234
    depends_on:
      - "mongodb"
    command : node app.js
    networks:
      - traefik

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes: 
      - ./volumes/db:/data/db
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_webgateway