version: '3'

services:
  proxy:
    container_name: traefik
    image: traefik
    restart: always    
    labels:
      - traefik.backend=proxy
      - traefik.frontend.rule=Host:traefik.local
    command: --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway
    ports:
      - 80:80
      - 8080:8080
      - 443:443


networks:
  webgateway:
    driver: bridge