version: '3'

services:

  #-PORTAINER
  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer:latest
    environment:
      - TZ=${GLOBAL_TZ} 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_DATA_VOLUME}:/data
    labels:
      - traefik.backend=portainer
      - traefik.frontend.rule=Host:portainer.${GLOBAL_DOMAIN}
    networks:
      - gateway_web

networks:
  gateway_web:
    external:
      name: gateway_web
