version: '3'

  portainer:
    container_name: portainer-application
    image: portainer/portainer
    restart: always  
    labels:
      - traefik.backend=portainer
      - traefik.frontend.rule=Host:portainer.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/docker-bay/volumes/portainer/data:/data
    networks:
      - traefik

  watchtower:
    container_name: portainer-watchtower
    image: v2tec/watchtower
    restart: always
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_webgateway
