version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - traefik
    ports:
      - "6379:6379"
    expose:
      - "6379"
    stdin_open: true
    tty: true
    labels:
      - "traefik.backend=redis"
      - "traefik.frontend.rule=Host:redis.local"
      
networks:
  traefik:
    external:
      name: traefik_webgateway
