version: '3'

services:
   mariadb:
     container_name: mariadb
     image: mariadb
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: example_database
       MYSQL_USER: mariadb-user
       MYSQL_PASSWORD: mariadb-user
    labels:
      - traefik.port=3306    
      - traefik.backend=mariadb
     volumes:
       - ~/docker-bay/volumes/mariadb-data:/var/lib/mysql
     networks:
       - traefik

networks:
  traefik:
    external:
      name: traefik_webgateway