version: '3.3'

services:
   dockerbay_mariadb:
     image: mariadb:latest
     container_name: "dockerbay-mariadb"
     volumes:
       - ~/docker-bay/volumes/mariadb-data:/var/lib/mysql
     restart: always
     networks:
       - traefik
     ports:
       - "13306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: dockerbay_db
       MYSQL_USER: dockerbayuser
       MYSQL_PASSWORD: dockerbayuser

networks:
  traefik:
    external:
      name: traefik_webgateway