version: '3.3'

services:
   mariadb:
     image: mariadb:latest
     container_name: "db-mariadb"
     volumes:
       - ~/docker-bay/volumes/mariadb-data:/var/lib/mysql
     restart: always
     networks:
       - traefik
     expose:
       - "3306"
     environment:
       MYSQL_ROOT_PASSWORD: mariadbroot
       MYSQL_DATABASE: mariadb_test
       MYSQL_USER: mariadb_user
       MYSQL_PASSWORD: mariadb_user_password

networks:
  traefik:
    external:
      name: traefik_webgateway