version: "3"

services:
  dockerbay_nodejs:
    build:
      context: ./
    image: dockerbay/nodejs
    container_name: "dockerbay-nodejs"
    user: "node"
    working_dir: /home/node/apps
    environment:
      - NODE_ENV=developement
    volumes:
      - ~/docker-bay/workspaces/nodejs:/home/node/apps
    ports:
      - "13000:3000"
    stdin_open: true
    tty: true
    networks:
      - traefik
    labels:
      - "traefik.port=3000"
      - "traefik.backend=dockerbay_nodejs"
      - "traefik.frontend.rule=Host:nodejs.dockerbay"

networks:
  traefik:
    external:
      name: traefik_webgateway