version: '3.3'

services:
   mysql:
     image: mysql:latest
     container_name: "db-mysql"
     volumes:
       - ~/docker-bay/volumes/mysql-data:/var/lib/mysql
     restart: always
     networks:
       - traefik
     expose:
       - "3306"
     environment:
       MYSQL_ROOT_PASSWORD: mysqlroot
       MYSQL_DATABASE: mysql_test
       MYSQL_USER: mysql_user
       MYSQL_PASSWORD: mysql_user_password

networks:
  traefik:
    external:
      name: traefik_webgateway