version: '3'

services:
   dockerbay_mysql:
     image: mysql:latest
     container_name: "dockerbay-mysql"
     volumes:
       - ~/docker-bay/volumes/mysql-data:/var/lib/mysql
     restart: always
     networks:
       - traefik
     ports:
       - "23306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: dockerbay_db
       MYSQL_USER: dockerbayuser
       MYSQL_PASSWORD: dockerbayuser

networks:
  traefik:
    external:
      name: traefik_webgateway